# All default values here based on usage within
# https://github.com/bgruening/docker-galaxy-stable.

galaxy_extras_install_packages: false

## Proftp Configuration.
proftpd_conf_path:  /etc/proftpd/proftpd.conf
proftpd_db_connection: galaxy@localhost
proftpd_db_username: galaxy
proftpd_db_password: galaxy
# Set proftpd_sql_auth_type to SHA1 if use_pbkd2=False in your galaxy.ini,
# or PBKDF2 if you have use_pbkd2=True or if you haven't changed the default.
# If you want to use PBKDF-2 you will need proftpd version 1.3.5rc3 or later
# (which is not available by default for ubuntu-12.04)
proftpd_sql_auth_type: SHA1
proftpd_welcome: "Public Galaxy FTP"
proftpd_files_dir: /export/ftp
proftpd_ftp_port: 21
proftpd_passive_port_low: 30000
proftpd_passive_port_high: 40000
# Set proftpd_use_sftp to true to use sftp instead of ftp
proftpd_use_sftp: false
proftpd_sftp_port: 22
# Set masquearade to true if host is NAT'ed.
proftpd_nat_masquerade: false
# proftpd_masquerade_address refefers to the ip that clients use to establish an ftp connection.
# Can be a command that returns an IP or an IP address and applies only if proftpd_nat_masquerade is true.
# ec2metadata --public-ipv4 returns the public ip for amazon's ec2 service.
proftpd_masquerade_address: "`ec2metadata --public-ipv4`"

use_pbkdf2: false
