version: '2'
services:
  # proftpd container
  proftpd:
    image: quay.io/galaxy/proftpd:compose
    environment:
        - proftpd_db_connection=galaxy@db
        - proftpd_db_username=galaxy
        - proftpd_db_password=chaopagoosaequuashie
        - proftpd_files_dir=/export/ftp
        - proftpd_use_sftp=True
        # WARNING: Do not use a large range. Docker might have a long startup time
        - proftpd_passive_port_low=30000
        - proftpd_passive_port_low=30010
    container_name: galaxy-proftp
    volumes:
        - ftp_data:/export/ftp
    ports:
        - "8021:21" # FTP
        - "8022:22" # SFTP
        - "30000-30010:30000-30010" # FTP Passive mode
    links:
        - postgres:db
    restart: always
    hostname: galaxy-proftpd

  # Database container
  postgres:
    image: postgres
    container_name: galaxy-postgres
    environment:
        - POSTGRES_PASSWORD=chaopagoosaequuashie
        - POSTGRES_USER=galaxy
        - POSTGRES_DB=galaxy
    volumes:
        - ./postgres-storage:/var/lib/postgresql/data
    hostname: galaxy-postgres


  # Main Galaxy container
  galaxy:
    image: quay.io/bgruening/galaxy:compose
    environment:
        #    Insert here your environment variables to change Galaxy's behaviour.
        #    For example to personalise Galaxy by changing the branding with
        #    - GALAXY_CONFIG_BRAND=FOO
        - NONUSE=proftp postgres
        - GALAXY_CONFIG_FTP_UPLOAD_DIR=/export/ftp
        - GALAXY_CONFIG_ALLOW_USER_DATASET_PURGE=True
        - GALAXY_CONFIG_ALLOW_LIBRARY_PATH_PASTE=True
        - GALAXY_CONFIG_ENABLE_USER_DELETION=True
        - GALAXY_CONFIG_ENABLE_BETA_WORKFLOW_MODULES=True
        - GALAXY_CONFIG_DATABASE_CONNECTION=postgresql://galaxy:chaopagoosaequuashie@db/galaxy?client_encoding=utf8
    ports:
        - "8080:80" # nginx
        - "9002:9002" # supervisor web-interface - not super useful in compose mode
    links:
        - postgres:db
    container_name: galaxy
    volumes:
        - ftp_data:/export/ftp
        # This is the directory where all your files from Galaxy will be stored
        # on your host system
        - ./galaxy-storage/:/export/
    hostname: galaxy
    privileged: True

volumes:
  ftp_data: {}
